Le but de cette activité est de réimplémenter une fonction de validation croisée.

On veut CrossValidation(model, hyperparameters, n_folds, scoring="accuracy")

In [100]:
import pandas as pd
import numpy as np

from sklearn import metrics

In [4]:
27//10

2

In [14]:
X = np.array([range(10), range(10)]).T
X[0:15, :]

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [99]:
class CrossValidation:
    def __init__(self, model, hyperparameters, n_folds=4, scoring="accuracy"):
        self.model = model
        self.hyperparameters = hyperparameters
        self.n_folds = n_folds
        self.scoring = scoring
        self.folds_index = self.__create_folds__(X)
        print(self.folds_index)
    
    def __create_folds__(self, X_or_y):
        # On veut séparer X en n_folds blocs.
        n = X_or_y.shape[0]
        q = n//self.n_folds+1
        folds = [i*q for i in range(self.n_folds)]
        
        return folds
    
    def fit(self, X, y):
        # Pour chaque bloc, on considère le reste du jeu de données et on entraîne notre modèle dessus.
        # Ensuite on teste notre modèle sur le bloc, et on garde en mémoire le score.
        for k in range(self.n_folds):
            i = self.folds_index[k]
            try:
                next_i = self.folds_index[(k+1)]
            except:
                next_i = -1
            
            if next_i != -1:
                X_train = np.concatenate((X[:i, :], X[next_i:, :]))
                X_test = X[i:next_i, :]
                y_train = np.concatenate((y[:i], y[next_i:]))
                y_test = y[i:next_i]
            else:
                X_train = X[:i, :]
                X_test = X[i:, :]
                y_train = y[:i]
                y_test = y[i:]
            
            # On s'occupe maintenant de train nos modèles
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            # A TERMINER.
    
cv = CrossValidation(None, None, n_folds = 4)
cv.fit(np.array([range(10), range(10)]).T, np.array(range(10)))

[0, 3, 6, 9]
0 3
[[3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]] [[0 0]
 [1 1]
 [2 2]]


3 6
[[0 0]
 [1 1]
 [2 2]
 [6 6]
 [7 7]
 [8 8]
 [9 9]] [[3 3]
 [4 4]
 [5 5]]


6 9
[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [9 9]] [[6 6]
 [7 7]
 [8 8]]


9 -1
[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]] [[9 9]]




In [45]:
np.array([range(10), range(10)]).T.shape

(10, 2)

In [94]:
10//4

2