In [1]:
import tensorflow as tf
import numpy as np

Everything is eager by default in tensorflow 2.0

In [3]:
a = np.array([1., 2.])
b = np.array([2., 5.])

tf.add(a, b)

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([3., 7.])>

## Graph Model : AutoGraph

In [5]:
@tf.function
def add_fc(a,b):
    return tf.add(a,b)

In [6]:
def add_fc(a,b):
    return tf.add(a,b)

print(tf.autograph.to_code(add_fc))

def tf__add_fc(a, b):
    with ag__.FunctionScope('add_fc', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = ag__.converted_call(ag__.ld(tf).add, (ag__.ld(a), ag__.ld(b)), None, fscope)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [7]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(256, activation="relu"))
model.add(tf.keras.layers.Dense(128, activation="relu"))
model.add(tf.keras.layers.Dense(10, activation="softmax"))

In [10]:
model_output = model.predict(np.zeros((1,30)))
model_output

1/1 [==============================] - 0s 78ms/step


array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]], dtype=float32)

In [11]:
model_output = model(np.zeros((1,30)))
model_output

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]], dtype=float32)>

In [14]:
@tf.function
def predict(x):
    return model(x)

model_output = predict(np.zeros((1,30)))
model_output

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]], dtype=float32)>